---
swagger: '2.0'
info:
  version: 1.0.0
  title: Keydesk server
basePath: /
paths:
  /token:
    post:
      produces:
        - application/json
      responses:
        201:
          description: Token created.
          schema:
            $ref: "#/definitions/token"
        500:
          description: 'Internal server error'
        default:
          description: error
          schema:
              $ref: "#/definitions/error"
  /user:
    get:
      security:
        - Bearer: []
      produces:
        - application/json
      responses:
        200:
          description: A list of users.
          schema:
              type: array
              items:
                  $ref: "#/definitions/user"
        403: 
          description: 'You do not have necessary permissions for the resource'
        500:
          description: 'Internal server error'
        default:
          description: error
          schema:
              $ref: "#/definitions/error"
    post:
      security:
        - Bearer: []
      produces:
        - application/octet-stream
      responses:
        201:
          description: New user created.
          schema:
              type: file
          headers:
              Content-Disposition:
                  type: string
                  description: the value is `attachment; filename="wg.conf"`
        403: 
          description: 'You do not have necessary permissions for the resource'
        500:
          description: 'Internal server error'
        default:
          description: error
          schema:
              $ref: "#/definitions/error"
  /user/{UserID}:
    delete:
      security:
        - Bearer: []
      produces:
        - application/json
      parameters:
        - type: string
          name: UserID
          in: path
          required: true
      responses:
        204:
          description: User deleted.
        403: 
          description: 'You do not have necessary permissions for the resource'
        500:
          description: 'Internal server error'
        default:
          description: error
          schema:
              $ref: "#/definitions/error"
definitions:
  token:
    type: object
    required:
      - Token
    properties:
      Token:
        type: string  
  user:
    type: object
    required:
      - UserID
      - UserName
      - CreatedAt
      - Status
      - MonthlyQuotaRemainingGB
    properties:
      UserID:
        type: string
      UserName:
        type: string
      Status:
        type: string
      Problems:
        type: array
        items:
          type: string
      CreatedAt:
        type: string
        format: date-time
      ThrottlingTill:
        type: string
        format: date-time
        x-nullable: true
      MonthlyQuotaRemainingGB:
        type: number
        format: float
      LastVisitHour:
        type: string
        format: date-time
        x-nullable: true
      LastVisitSubnet:
        type: string
      LastVisitASName:
        type: string
      LastVisitASCountry:
        type: string
      PersonName:
        type: string
      PersonDesc:
        type: string
      PersonDescLink:
        type: string
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
      message:
        type: string
        
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header